# Generated by Django 3.2 on 2021-05-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_blog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='1.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
